---
- hosts: dcnm
  gather_facts: no
  connection: ansible.netcommon.httpapi
  vars:
    ansible_connection: ansible.netcommon.httpapi
    ansible_network_os: cisco.dcnm.dcnm
    ansible_user: "anshul"
    ansible_password: "admincisco!23"
    ansible_domain: local
    ansible_python_interpreter: python3
    ansible_httpapi_validate_certs: False
    ansible_httpapi_use_ssl: True
    ansible_httpapi_login_domain: local
    ansible_command_timeout: 120
  tasks:
# To create or modify templates
    - name: Create or modify templates
      cisco.dcnm.dcnm_template:
        state: merged        # only choose form [merged, deleted, query]
        config:
          - name: template_101
            description: "Template_101"
            tags: "internal policy 101"
            content: |
              telemetry
                certificate /bootflash/telegraf.crt telegraf
                destination-profile
                  use-vrf management
                destination-group 101
                  ip address 10.195.225.176 port 57101 protocol gRPC encoding GPB
                sensor-group 101
                  data-source DME
                  path sys/ch depth unbounded                
                subscription 101
                  dst-grp 101
                  snsr-grp 101 sample-interval 10101
          # - name: template_102
          #   description: "Template_102"
          #   tags: "internal policy 102"
          #   content: |
          #     telemetry
          #       certificate /bootflash/telegraf.crt telegraf
          #       destination-profile
          #         use-vrf management
          #       destination-group 1
          #         ip address 10.195.225.102 port 57102 protocol gRPC encoding GPB
          #       sensor-group 102
          #         data-source DME
          #         path sys/ch depth unbounded
          #       subscription 102
          #         dst-grp 102
          #         snsr-grp 102 sample-interval 10102
